#!/bin/bash

alias vim="nvim"
alias vi="nvim"
alias grep="rg"
alias ls="eza"
alias g="git"
alias cp="cp -i"
alias mv="mv -i"
alias untar="tar -xvf"

pbcopy() {
	stdin=$(</dev/stdin);
	pbcopy="$(which pbcopy)";
	if [[ -n "$pbcopy" ]]; then
		echo "$stdin" | "$pbcopy"
	else
		echo "$stdin" | xclip -selection clipboard
	fi
}

pbpaste() {
	pbpaste="$(which pbpaste)";
	if [[ -n "$pbpaste" ]]; then
		"$pbpaste"
	else
		xclip -selection clipboard
	fi
}