# if [ "$TERM_PROGRAM" != "vscode" ]; then
#     eval "$(zellij setup --generate-auto-start zsh)"
# fi

### setup environment variables
export -U PATH path FPATH fpath MANPATH manpath
export -UT INFOPATH infopath

export SHELDON_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/sheldon/zsh"

source "$XDG_CONFIG_HOME"/shell/shared/env
source "$XDG_CONFIG_HOME"/shell/shared/alias


# # add zsh completion
# eval "$(uv generate-shell-completion zsh)"
# fpath+="$XDG_CONFIG_HOME"/zsh/completions

### commands & aliases
setopt AUTO_CD
autoload -U compinit && compinit -d "$XDG_CACHE_HOME"/zsh/zcompdump-"$ZSH_VERSION"

# # 1password
export LS_COLORS="$(vivid generate nord)"


eval "$(oh-my-posh init zsh)"
eval "$(sheldon source)"
eval "$(zoxide init --cmd cd zsh)"
eval "$(direnv hook zsh)"
eval "$(atuin init zsh)"