format = """
$directory$hostname
$character
"""

right_format = """
$git_branch\
$git_commit\
$git_state\
$git_status\
"""

continuation_prompt = '▶▶ '

[package]
disabled = true

[hostname]
format = 'on [$hostname](bold dimmed green)'

[git_branch]
format = '[$branch(:$remote_branch)]($style) '
